# NGINX reçoit les requêtes HTTPS, sert les fichiers statiques directement, et envoie les fichiers PHP à WordPress via PHP-FPM.
http {
    server {
        listen 443 ssl;              # écoute sur le port 443 en HTTPS
        server_name mobougri.42.fr;  # nom de domaine du site

        # Certificat SSL
        ssl_certificate     /etc/ssl/certs/nginx.crt;
        ssl_certificate_key /etc/ssl/private/nginx.key;
        ssl_protocols       TLSv1.2 TLSv1.3;  # uniquement TLS 1.2 et 1.3

        root /var/www/wordpress;  # dossier des fichiers WordPress
        index index.php;          # fichier par défaut

        location / {
            try_files $uri $uri/ /index.php?$args;
            # cherche le fichier demandé, sinon redirige vers index.php
        }

        location ~ \.php$ {
            fastcgi_pass wordpress:9000;  # envoie les fichiers PHP au conteneur wordpress via PHP-FPM
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param HTTPS on;       # dit à WordPress qu'on est en HTTPS
        }
    }
}
events {}  # obligatoire dans nginx.conf même si vide