[www]
user = www-data       # PHP-FPM tourne avec l'utilisateur www-data
group = www-data      # et le groupe www-data (sécurité)

listen = 0.0.0.0:9000  # écoute sur le port 9000 sur toutes les interfaces
                        # permet à NGINX de se connecter depuis un autre conteneur

pm = dynamic           # gestion dynamique des processus PHP
pm.max_children = 5    # maximum 5 processus PHP en parallèle
pm.start_servers = 2   # 2 processus au démarrage
pm.min_spare_servers = 1  # minimum 1 processus en attente
pm.max_spare_servers = 3  # maximum 3 processus en attente